jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-install
      - uses: JoshuaKGoldberg/all-contributors-auto-action@v0.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

name: Contributors

on:
  push:
    branches:
      - main
